language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose --release
  - cargo test --verbose --release
  - cargo build --verbose --release --no-default-features
  - cargo test --verbose --release --no-default-features
