[package]
name = "blake2-rfc"
version = "0.2.1"
authors = ["Cesar Eduardo Barros <cesarb@cesarb.eti.br>"]
description = "A pure Rust implementation of BLAKE2 based on the draft RFC."
repository = "https://github.com/cesarb/blake2-rfc"
readme = "README.md"
keywords = ["blake2", "blake2b", "blake2s", "hash", "crypto"]
license = "MIT"

[dependencies]
constant_time_eq = "0.1.0"

[dev-dependencies]
rustc-serialize = "0.3.15"
